backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Category", name: "category", widget: "hidden", default: "posts"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Category", name: "category", widget: "hidden", default: "posts"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string"}
